# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-24 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20171024_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='time',
        ),
        migrations.RemoveField(
            model_name='commentpost',
            name='time',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentpost',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
