# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-24 19:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20171025_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateField(default=datetime.date(2017, 10, 24)),
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='date',
            field=models.DateField(default=datetime.date(2017, 10, 24)),
        ),
    ]
